# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

def notify(subtitle, message)
	notification(
		title: "Fastlane",
		subtitle: subtitle,
		message: message, 
		sound: "Pop"
		)
end

def swiftlint()
	swiftlint(
		mode: :lint,
		output_file: "swiftlint.result.json",
		raise_if_swiftlint_error: true, 
		ignore_exit_status: true
		)
end

platform :ios do
  desc "Builds the project, runs unit tests"
  lane :build_lane do
    ensure_env_vars(
        env_vars: ['SCHEME', 'BUNDLE_IDENTIFIER']
    )
    	swiftlint
	build = increment_build_number
	branch = git_branch
	build_name = get_version_number + "." + build
    	scheme = ENV['SCHEME']
	message = scheme + " " + branch + " " + build_name
	
	notify("Started building", message)
	xcbuild
	scan(devices: ["iPhone 8"], scheme: scheme)
	notify("Built", message)
  end
end
